#!/bin/bash

##
# Sigrok Wrapper CLI Tool
# Christopher Apodaca
# Sep 25, 2020
# MIT License
##

# TIMESTAMP GLOBALS
IS_TIME=0

# INTEGER REGEX
INT_REGX='^[0-9]+$'

# OUTPUT FORMAT 
IS_OUTPUT=0
OUTPUT_SIZE=0
OUTPUT_ARG="--continuous"

# RPM GLOBALS
IS_RATIO=0
RATIO=1

while [ -n "$1" ]; do
	case "$1" in
	--helpme | -hm)
		echo "-r | --reload  to reload USB Connection (usb_modeswitch --reset-usb)"
		exit
		;;

	--reload | -r)
		shift 1
		USB_ID=$(lsusb | grep 'Qin' | cut -d" " -f6 | sed -e 's/:/./g')
		USB_VID=$(echo $USB_ID | cut -d"." -f1)
		USB_PID=$(echo $USB_ID | cut -d"." -f2)
		USB_MODESWITCH=$(usb_modeswitch -v 0x$USB_VID -p 0x$USB_PID --reset-usb)

		echo "RESTARTING USB: $USB_ID"
		echo "$USB_MODESWITCH"
		;;

	--timestamp)
		shift 1
		echo "INVOKING TIME STAMPS"
		IS_TIME=1
		;;

	--output)
		shift 1
		IS_OUTPUT=1

		if [[ $1 =~ $INT_REGX ]]; then
			OUTPUT_SIZE=$1
			shift 1
		fi
		;;

	--ratio)
		shift 1
		echo "INVOKING RATIO"
		IS_RATIO=1

		if [[ $1 =~ $INT_REGX ]]; then
			RATIO=$1
			shift 1
		fi
		;;

		*)
		break
		;;
	esac

done

QIN=$(lsusb | grep 'Qin' | cut -d" " -f2,4 | cut -d ":" -f1 | sed -e 's/ /./g')
MY_DRIVER="uni-t-ut372:conn="
DRIVER_PARAMS="$MY_DRIVER$QIN "
PARENT_ARGS="$*"


## PARAMS LOGIC
if [ $IS_TIME = 1 ]; then
	TIME_ARG="| xargs -L 1 bash -c 'printf \"[%s] %s\n\" \"\$(date +%s.%N)\" \"\$*\" ' bash "
fi

if [[ $IS_OUTPUT = 1 && $OUTPUT_SIZE -gt 0 ]]; then
	OUTPUT_ARG="--samples $OUTPUT_SIZE"
fi

if [ $IS_RATIO = 1 ]; then
	FIELD="2"

	if [[ $IS_TIME = 1 ]]; then
		FIELD="3"
	fi

	GREP_ARG="grep P1"
	CUT_ARG="cut -d' ' -f${FIELD}"
	AWK_ARG="awk -v c=${RATIO} '{ \$0 /= c; print \$0 }' OFS='\n' "

	RATIO_ARG="| $GREP_ARG | $CUT_ARG | $AWK_ARG"
	PAREN_ARGS=""
fi

# EXECUTE
EXECUTE="sigrok-cli -d $DRIVER_PARAMS $OUTPUT_ARG $TIME_ARG $RATIO_ARG $PARENT_ARGS "
eval $EXECUTE
